#!/usr/bin/env python

from __future__ import print_function
import sys
import os
import subprocess

JARS = ["droidsafe-core.jar","droidsafe-libs.jar"]
MAIN_CLASS = "droidsafe.main.Main"
APAC_HOME = os.environ['APAC_HOME'] + os.sep

def run_droidsafe(args):
    libs = APAC_HOME + "bin" + os.sep
    command = []
    command.append("java")
    command.append("-cp")

    jars = "";
    for jar in JARS:
    	jars += libs + jar + ":";
    jars += "."
    command.append(jars)

    command.append(MAIN_CLASS)

    for arg in args[1:]:
        command.append(arg)

    #print(command)
    subprocess.call(command)
    return



def check_env_vars(): 
    if not "ANDROID_SDK_HOME" in os.environ:
        print("Need to set ANDROID_SDK_HOME to the root of your android sdk installation.")
        sys.exit(1)
        
    if not "APAC_HOME" in os.environ:
        print("Need to set APAC_HOME to the root of your apac repository.")
        sys.exit(1)

# Gather our code in a main() function
def main():
    check_env_vars()
    run_droidsafe(sys.argv)


# Standard boilerplate to call the main() function to begin
# the program.
if __name__ == '__main__':
    main()
