#!/usr/bin/env bash

#must be in parent directory of application root
#takes one argument

#-kobjsens 2, 3, 4
#-noclinitcontext
#-ignorenocontextflows
#-allcontext
#-typesforcontext
#-trackallflows (looks good for general use)

num_tests=2
app_dir=${1?"Need root directory arg"}
app_name=${2?"Need app name"}
apac_home=${APAC_HOME?"Need to define APAC_HOME"}
args_file_name="ds.rt.addtional.args"

function create_config() {
    # $1 is test name
    # $2 is test parameters to be writter to file
    
    test_dir="$app_name"-"$1"

    # copy root dir to directory with test name appended
    echo "$test_dir"
    cp -R "$app_dir" "$test_dir"

    # create parameters file
    echo "$2" > "$test_dir"/"$args_file_name"
    
    
}

args0="-kobjsens 2
-nojsa 
-nova
-noclinitcontext
-ignorenocontextflows
-trackallflows"
create_config "2obj-noclinit-nova" "$args0"

args1="-kobjsens 3
-nojsa 
-nova
-noclinitcontext
-ignorenocontextflows
-trackallflows"
create_config "3obj-noclinit-nova" "$args1"

${apac_home}/system-tests/regtest.py -threads $num_tests -timeout 28800 -dir .

# args2="-kobjsens 3
# -allcontext
# -noclinitcontext
# -trackallflows"
# create_config  "3obj-allcontext-noclinit-trackall" "$args2"

# args3="-kobjsens 3
# -allcontext
# -trackallflows"
# create_config  "3obj-allcontext-trackall" "$args3"







