package droidsafe.annotations;

public enum DSSinkKind {
    ACCOUNT_SETTINGS,
    AUDIO,
    BLUETOOTH,
    BROWSER_INFORMATION,
    CALENDAR_INFORMATION,
    CONTACT_INFORMATION,
    EMAIL,
    FILE,
    LOCATION_INFORMATION,
    LOG,
    NETWORK,
    NFC,
    NO_CATEGORY,
    OS_COMMAND,
    PHONE_CONNECTION,
    PHONE_STATE,
    SCREEN,
    SMS_MMS,
    START_ACTIVITY,
    SYNCHRONIZATION_DATA,
    SYSTEM_SETTINGS,
    VOIP,
    UNSPECIFIED
}
